from __future__ import annotations

from datetime import datetime
from decimal import Decimal
from typing import TYPE_CHECKING
from uuid import UUID

from sqlalchemy import CheckConstraint, DateTime, Numeric, String, func
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base

if TYPE_CHECKING:
    from app.models.portfolio import Portfolio
    from app.models.price_history import PriceHistory


class User(Base):
    """Application-side user profile.

    `id` matches `auth.users.id` from Supabase — set by `POST /auth/sync`,
    never generated by this database.
    """

    __tablename__ = "users"

    id: Mapped[UUID] = mapped_column(PG_UUID(as_uuid=True), primary_key=True)
    email: Mapped[str] = mapped_column(String, nullable=False)
    display_name: Mapped[str | None] = mapped_column(String, nullable=True)
    avatar_url: Mapped[str | None] = mapped_column(String, nullable=True)

    preferred_currency: Mapped[str] = mapped_column(
        String, nullable=False, server_default="AED"
    )
    timezone: Mapped[str] = mapped_column(
        String, nullable=False, server_default="Asia/Dubai"
    )
    default_pricing_mode: Mapped[str] = mapped_column(
        String, nullable=False, server_default="live"
    )

    manual_gold_rate_per_gram: Mapped[Decimal | None] = mapped_column(
        Numeric(14, 4), nullable=True
    )
    manual_silver_rate_per_gram: Mapped[Decimal | None] = mapped_column(
        Numeric(14, 4), nullable=True
    )
    manual_rates_currency: Mapped[str | None] = mapped_column(String, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    portfolio: Mapped[Portfolio | None] = relationship(
        "Portfolio",
        back_populates="user",
        cascade="all, delete-orphan",
        uselist=False,
        lazy="raise",
    )
    manual_prices: Mapped[list[PriceHistory]] = relationship(
        "PriceHistory",
        back_populates="user",
        cascade="all, delete-orphan",
        lazy="raise",
    )

    __table_args__ = (
        CheckConstraint(
            "preferred_currency IN ('AED','USD','EUR','GBP','SAR','INR')",
            name="ck_users_preferred_currency",
        ),
        CheckConstraint(
            "default_pricing_mode IN ('live','manual')",
            name="ck_users_default_pricing_mode",
        ),
    )
